---
layout: post
title: TDDBE - xUnit 22장
date: 2008-09-01 11:30:26.000000000 -07:00
type: post
parent_id: '0'
published: true
password: ''
status: publish
categories:
- Coding
tags:
- TDD
- xUnit
meta:
  arkayne-cache-post: |2+







    <!-- BlogGlue Plugin Error -->
    <!-- This page cannot be linked by BlogGlue. -->
    <!-- You need a valid token. Get one at the URL below. -->
    <!-- http://www.blogglue.com/login/ -->

















  arkayne-time-post: '1323146878'
author:
  login: whiteship
  email: whiteship2000@gmail.com
  display_name: 기선
  first_name: 기선
  last_name: 백
---
<p>ToDo<br />실패한 테스트 보고하기</p>
<p>TestResult에서 실패한 테스트 갯수를 세는 메소드 부터 테스트합니다.</p>
<div style="border: 1px solid rgb(144, 224, 255); padding: 10px; background-color: rgb(210, 242, 255);">&nbsp; &nbsp; public void testFailedResultFormatting(){<br />&nbsp; &nbsp; &nbsp; &nbsp; TestResult result = new TestResult();<br />&nbsp; &nbsp; &nbsp; &nbsp; result.testStarted();<br />&nbsp; &nbsp; &nbsp; &nbsp; result.testFailed();<br />&nbsp; &nbsp; &nbsp; &nbsp; assert result.summary().equals("1 run, 1 failed");<br />&nbsp; &nbsp; }</div>
<p>TestResult의 메소드가 갯수를 잘 세고 있는지 확인합니다. 구현은 간단합니다.</p>
<div style="border: 1px solid rgb(128, 184, 136); padding: 10px; background-color: rgb(202, 238, 206);">public class TestResult {</p>
<p>&nbsp; &nbsp; int runCount;<br />&nbsp; &nbsp; int failedCount;<br />&nbsp; &nbsp; <br />&nbsp; &nbsp; public void testStarted(){<br />&nbsp; &nbsp; &nbsp; &nbsp; this.runCount += 1;<br />&nbsp; &nbsp; }</p>
<p>&nbsp; &nbsp; public void testFailed() {<br />&nbsp; &nbsp; &nbsp; &nbsp; this.failedCount += 1;<br />&nbsp; &nbsp; }</p>
<p>&nbsp; &nbsp; public String summary() {<br />&nbsp; &nbsp; &nbsp; &nbsp; return runCount + " run, " + failedCount + " failed";<br />&nbsp; &nbsp; }</p>
<p>}</p></div>
<p>그리고 이제 실패하는 테스트 결과를 확인하는 테스트를 작성합니다.</p>
<div style="border: 1px solid rgb(144, 224, 255); padding: 10px; background-color: rgb(210, 242, 255);">&nbsp; &nbsp; public void testFailedResult(){<br />&nbsp; &nbsp; &nbsp; &nbsp; test = new WasRun("testBrokenMethod");<br />&nbsp; &nbsp; &nbsp; &nbsp; TestResult result = test.run();<br />&nbsp; &nbsp; &nbsp; &nbsp; assert result.summary().equals("1 run, 1 failed");<br />&nbsp; &nbsp; }</div>
<p>총. 1개를 실행했는데, 1개가 실패한 겁니다. 일단, WasRun 클래스에 예외를 발생시키는(실패하는) 테스트를 추가합니다.</p>
<div style="border: 1px solid rgb(128, 184, 136); padding: 10px; background-color: rgb(202, 238, 206);">&nbsp; &nbsp; public void testBrokenMethod() throws RuntimeException&nbsp; {<br />&nbsp; &nbsp; &nbsp; &nbsp; throw new RuntimeException("예외 발생하는&nbsp; 테스트");<br />&nbsp; &nbsp; }</div>
<p>그리고 TestCase의 run() 메소드에서 예외가 발생할 때마다 TestResult에 처음에 만들어 둔 testFailed()를 호출합니다.</p>
<div style="border: 1px solid rgb(128, 184, 136); padding: 10px; background-color: rgb(202, 238, 206);">&nbsp; &nbsp; &nbsp; &nbsp; try {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Method method = this.getClass().getMethod(methodName, null);<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; method.invoke(this, null);<br />&nbsp; &nbsp; &nbsp; &nbsp; } catch (InvocationTargetException e) {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; result.testFailed();<br />&nbsp; &nbsp; &nbsp; &nbsp; } catch (Exception e) {<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; throw new RuntimeException(e);<br />&nbsp; &nbsp; &nbsp; &nbsp; }</div>
<p>예외를 잡는 부분에 대해서 조금 고민을 했는데, InvocationTargetExcepion만 따로 잡고, 나머진 일단 덩어리로 처리해버렸습니다. 어차피 세세하게 분리를 해놔도 각각의 catch 블럭에서 전부 throw new Runtime(e); 으로 구현할꺼기 때문에, 저렇게 덩어리로 잡아버렸습니다.</p>
<p></p>
